Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Software_2.Models;
using Software_2.Data;

namespace Software_2.Controllers
{
    public class ClienteController : Controller
    {

       private readonly ILogger<ClienteController> _logger;
       private readonly InventarioContext _context;


        public ClienteController(ILogger<ClienteController> logger,
            InventarioContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }


        public async Task<IActionResult> Listar(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewBag.CurrentSort = sortOrder;
                var clientes = from c in _context.Cliente
                    select c;
                if (!String.IsNullOrEmpty(searchString))
                {
                    clientes = clientes.Where(c => c.Nombre.Contains(searchString)
                                || c.Celular.Contains(searchString)  || c.Direccion.Contains(searchString) || c.Cantidad.ToString().Contains(searchString));
                }

                if (searchString != null)
                {
                    pageNumber  = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;
                   

                int pageSize = 10;
                    return View(await PaginatedList<Cliente>.CreateAsync(clientes.AsNoTracking(), pageNumber ?? 1, pageSize));

       
        }
                
        // GET: Contacto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nombre,Celular,Direccion,Cantidad")] Cliente cliente)
        {
            if (id != cliente.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                    
                }
                
                TempData["prueba02"] = "prueba02";

                return RedirectToAction(nameof(Listar));

            }
            return View(cliente);
        }
        

        public IActionResult Delete(int? id)
        {
            var Cliente = _context.Cliente.Find(id);
            _context.Cliente.Remove(Cliente);
            _context.SaveChanges();
            return RedirectToAction(nameof(Listar));
        }

        public IActionResult Enviar(Cliente objFormulario)
        {
              if (ModelState.IsValid)
                {
                _context.Add(objFormulario);
                _context.SaveChanges();
                TempData["prueba"] = "prueba01";
                objFormulario.Respuesta = "Gracias. Formulario enviado";
                return RedirectToAction("Listar");  
                }
            return View("index", objFormulario);
        }
    }
}

Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Software_2.Models;
using Software_2.Data;
namespace Software_2.Controllers
{
    public class ProductoController : Controller
    {

       private readonly ILogger<ProductoController> _logger;
       private readonly InventarioContext _context;


        public ProductoController(ILogger<ProductoController> logger,
            InventarioContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult RegistrarSalidaCalzado()
        {
            return View();
        }

        public IActionResult Estado()
        {
           var listProductos=_context.RegistroS.ToList();
            return View(listProductos);
        }

        public IActionResult Salidas()
        {
            var listProductos=_context.RegistroS.ToList();
            return View(listProductos);
        }

        public async Task<IActionResult> MostrarCaracteristica(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registrarH = await _context.RegistrarH.FindAsync(id);
            if (registrarH == null)
            {
                return NotFound();
            }
            return View(registrarH);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult MostrarCaracteristica(int id, [Bind("ID,Nombre,Codigo,Color,Tipo,Descripcion,Talla40,Talla41,Talla42,Talla43")] ProductoH registrarH)
        {
            if (id != registrarH.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                    
                }
                TempData["prueba02"] = "prueba02";
                return RedirectToAction(nameof(ListarH));
            }
            return View(registrarH); 

        }


        public IActionResult InventarioH()
        {
            var listProductos=_context.RegistrarH.ToList();
            return View(listProductos);
        }

        public IActionResult InventarioM()
        {
            var listProductos=_context.RegistrarM.ToList();
            return View(listProductos);
        }

        public IActionResult InventarioN()
        {
            var listProductos=_context.RegistrarN.ToList();
            return View(listProductos);
        }
        
        public IActionResult Registrar(RegistroS objFormulario)
        {
              if (ModelState.IsValid)
                {
                _context.Add(objFormulario);
                _context.SaveChanges();
                TempData["prueba"] = "prueba01";
                objFormulario.Respuesta = "Gracias. Formulario enviado";
                return RedirectToAction("Salidas");  
                }
            return View("RegistrarSalidaCalzado", objFormulario);
        }

        public async Task<IActionResult> ListarH(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewBag.CurrentSort = sortOrder;
                var registrarH = from s in _context.RegistrarH
                    select s;
                if (!String.IsNullOrEmpty(searchString))
                {
                    registrarH = registrarH.Where(s => s.Nombre.Contains(searchString)
                                || s.Codigo.Contains(searchString)  || s.Color.Contains(searchString) || s.Tipo.Contains(searchString) || s.Descripcion.Contains(searchString)
                                || s.Talla40.ToString().Contains(searchString) || s.Talla41.ToString().Contains(searchString) || s.Talla42.ToString().Contains(searchString)
                                || s.Talla43.ToString().Contains(searchString) );
                }

                if (searchString != null)
                {
                    pageNumber  = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;
                   

                int pageSize = 10;
                    return View(await PaginatedList<ProductoH>.CreateAsync(registrarH.AsNoTracking(), pageNumber ?? 1, pageSize));

       
        }

         public async Task<IActionResult> ListarM(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewBag.CurrentSort = sortOrder;
                var registrarM = from s in _context.RegistrarM
                    select s;
                if (!String.IsNullOrEmpty(searchString))
                {
                    registrarM = registrarM.Where(s => s.Nombre.Contains(searchString)
                                || s.Codigo.Contains(searchString)  || s.Color.Contains(searchString) || s.Tipo.Contains(searchString) || s.Descripcion.Contains(searchString)
                                || s.Talla35.ToString().Contains(searchString) || s.Talla36.ToString().Contains(searchString)
                                || s.Talla37.ToString().Contains(searchString) || s.Talla38.ToString().Contains(searchString) || s.Talla39.ToString().Contains(searchString));
                }

                if (searchString != null)
                {
                    pageNumber  = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;
                   

                int pageSize = 10;
                    return View(await PaginatedList<ProductoM>.CreateAsync(registrarM.AsNoTracking(), pageNumber ?? 1, pageSize));

       
        }

         public async Task<IActionResult> ListarN(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewBag.CurrentSort = sortOrder;
                var registrarN = from s in _context.RegistrarN
                    select s;
                if (!String.IsNullOrEmpty(searchString))
                {
                    registrarN = registrarN.Where(s => s.Nombre.Contains(searchString)
                                || s.Codigo.Contains(searchString)  || s.Color.Contains(searchString) || s.Sexo.Contains(searchString) 
                                || s.Tipo.Contains(searchString) || s.Descripcion.Contains(searchString)
                                || s.Talla25.ToString().Contains(searchString) || s.Talla26.ToString().Contains(searchString) || s.Talla27.ToString().Contains(searchString)
                                || s.Talla28.ToString().Contains(searchString)  || s.Talla29.ToString().Contains(searchString)  || s.Talla30.ToString().Contains(searchString) );
                }

                if (searchString != null)
                {
                    pageNumber  = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;
                   

                int pageSize = 10;
                    return View(await PaginatedList<ProductoN>.CreateAsync(registrarN.AsNoTracking(), pageNumber ?? 1, pageSize));

       
        }

        public IActionResult DeleteH(int? id)
        {
            var registrarH = _context.RegistrarH.Find(id);
            _context.RegistrarH.Remove(registrarH);
            _context.SaveChanges();
            return RedirectToAction(nameof(ListarH));
        }

        public IActionResult DeleteM(int? id)
        {
            var registrarM = _context.RegistrarM.Find(id);
            _context.RegistrarM.Remove(registrarM);
            _context.SaveChanges();
            return RedirectToAction(nameof(ListarM));
        }

        public IActionResult DeleteN(int? id)
        {
            var registrarN = _context.RegistrarN.Find(id);
            _context.RegistrarN.Remove(registrarN);
            _context.SaveChanges();
            return RedirectToAction(nameof(ListarN));
        }


          public async Task<IActionResult> AsignarCaracteristica(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registrarH = await _context.RegistrarH.FindAsync(id);
            if (registrarH == null)
            {
                return NotFound();
            }
            return View(registrarH);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AsignarCaracteristica(int id, [Bind("ID,Nombre,Codigo,Color,Tipo,Descripcion,Talla40,Talla41,Talla42,Talla43")] ProductoH registrarH)
        {
            if (id != registrarH.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(registrarH);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                    
                }
                TempData["prueba02"] = "prueba02";
                return RedirectToAction(nameof(ListarH));
            }
            return View(registrarH);
        }

        public async Task<IActionResult> EditM(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registrarM = await _context.RegistrarM.FindAsync(id);
            if (registrarM == null)
            {
                return NotFound();

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title >@ViewData["Title"] - MALK</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/materia/bootstrap.min.css" integrity="sha384-B4morbeopVCSpzeC1c4nyV0d0cqvlSAfyXVfrPJa25im5p+yEN/YmhlgQP/OyMZD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.0.1/materia/bootstrap.min.css" integrity="sha512-/y9oobSJRht6yOWV3xQfrbGPb+Df9PnvgaNK3lICsNl564dwu9aWtOlZnzRxOlKNd1bYCFkGC1bjdHuPM0dLnw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark">
    <div class="container">
      <a class="navbar-brand text-light font-weight-bold"  asp-controller="Home" asp-action="Productos" >MALK</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="icon ion-md-menu lead text-light"></i>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item mr-2">
            <a class="nav-link text-light" asp-controller="Home" asp-action="Productos" >Productos</a>
          </li>
          <li class="nav-item mr-2">
            <a class="nav-link text-light" asp-controller="Producto" asp-action="ListarH">Hombres</a>
          </li>
          <li class="nav-item mr-2">
            <a class="nav-link text-light" asp-controller="Producto" asp-action="ListarM">Mujeres</a>
          </li>
          <li class="nav-item mr-2">
            <a class="nav-link text-light" asp-controller="Producto" asp-action="ListarN">Niños</a>
          </li>
          <li class="nav-item mr-2">
            <a class="nav-link text-light" asp-controller="Producto" asp-action="Estado" >Estado</a>
          </li>
           <li class="nav-item mr-2">
            <a class="nav-link text-light" asp-controller="Producto" asp-action="Salidas" >Salidas de Calzado</a>
          </li>  
            <li class="nav-item mr-2">
            <a class="nav-link text-light" asp-controller="Cliente" asp-action="Listar">Clientes</a>
          </li>


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle show" style="color: white;" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true">Inventario</a>
          <div class="dropdown-menu show" data-bs-popper="none">
            <a class="dropdown-item"  asp-controller="Producto" asp-action="InventarioH">Hombres</a>
            <a class="dropdown-item"  asp-controller="Producto" asp-action="InventarioM">Mujeres</a>
            <a class="dropdown-item"  asp-controller="Producto" asp-action="InventarioN">Niños</a>
        </li>

        </ul>
      </div>
    </div>
  </nav>  
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>